name:
  value: nebrass

spring:
  cloud:
    config:
      override-system-properties: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

custom:
  service:
    message: "Welcome to the Eureka Application (Dev)"
